apiVersion: testing.stacks.org/v1beta1
kind: FaultCampaign
metadata:
  name: signer-1-dns-error
spec:
  networkRef: attacknet
  safety:
    maxUnavailableSignerBasisPoints: 3000
    maxUnavailableMinerBasisPoints: 0
    maxConcurrentFaults: 1
    allowQuorumLoss: false
    allowBurnchain: false
    allowExtendedDuration: false
    allowExtremeSeverity: false
    allowMinerMajorityOutage: false
    allowUnenrolledNetworkTargets: false
  stages:
    - id: signer-dns-error
      faults:
        - id: signer-dns
          target:
            actors: [signer-1]
            mode: all
          fault:
            type: dns
            action: error
            mode: all
            duration: 30s
            parameters:
              patterns: [attacknet-signer-node-1.hacknet-system.svc.cluster.local]
