pub mod mainnet;
pub mod params;
pub mod regtest;
pub mod testnet;

pub use mainnet::{
    BITCOIN_MAINNET_FIRST_BLOCK_HASH, BITCOIN_MAINNET_FIRST_BLOCK_HEIGHT,
    BITCOIN_MAINNET_FIRST_BLOCK_TIMESTAMP, BITCOIN_MAINNET_GENESIS_BURN_HEIGHT,
    BITCOIN_MAINNET_INITIAL_REWARD_START_BLOCK, BITCOIN_MAINNET_STACKS_2_05_BURN_HEIGHT,
    BITCOIN_MAINNET_STACKS_21_BURN_HEIGHT, BITCOIN_MAINNET_STACKS_22_BURN_HEIGHT,
    BITCOIN_MAINNET_STACKS_23_BURN_HEIGHT, BITCOIN_MAINNET_STACKS_24_BURN_HEIGHT,
    BITCOIN_MAINNET_STACKS_25_BURN_HEIGHT, BITCOIN_MAINNET_STACKS_30_BURN_HEIGHT,
    BITCOIN_MAINNET_STACKS_31_BURN_HEIGHT, BITCOIN_MAINNET_STACKS_32_BURN_HEIGHT,
    BITCOIN_MAINNET_STACKS_33_BURN_HEIGHT, BITCOIN_MAINNET_STACKS_34_BURN_HEIGHT,
    BITCOIN_MAINNET_STACKS_40_BURN_HEIGHT, BITCOIN_MAINNET_STACKS_41_BURN_HEIGHT,
    C32_ADDRESS_VERSION_MAINNET_MULTISIG, C32_ADDRESS_VERSION_MAINNET_SINGLESIG,
    epoch_schedule as mainnet_epoch_schedule,
};
pub use params::EpochScheduleLimits;
pub use regtest::{
    BITCOIN_REGTEST_FIRST_BLOCK_HASH, BITCOIN_REGTEST_FIRST_BLOCK_HEIGHT,
    BITCOIN_REGTEST_FIRST_BLOCK_TIMESTAMP, epoch_schedule as regtest_epoch_schedule,
};
pub use stacks_primitives::network::{Mainnet, Regtest, StacksNetwork, Testnet};
pub use testnet::{
    BITCOIN_TESTNET_FIRST_BLOCK_HASH, BITCOIN_TESTNET_FIRST_BLOCK_HEIGHT,
    BITCOIN_TESTNET_FIRST_BLOCK_TIMESTAMP, BITCOIN_TESTNET_GENESIS_BURN_HEIGHT,
    BITCOIN_TESTNET_STACKS_2_05_BURN_HEIGHT, BITCOIN_TESTNET_STACKS_21_BURN_HEIGHT,
    BITCOIN_TESTNET_STACKS_22_BURN_HEIGHT, BITCOIN_TESTNET_STACKS_23_BURN_HEIGHT,
    BITCOIN_TESTNET_STACKS_24_BURN_HEIGHT, BITCOIN_TESTNET_STACKS_25_BURN_HEIGHT,
    BITCOIN_TESTNET_STACKS_30_BURN_HEIGHT, BITCOIN_TESTNET_STACKS_31_BURN_HEIGHT,
    BITCOIN_TESTNET_STACKS_32_BURN_HEIGHT, BITCOIN_TESTNET_STACKS_33_BURN_HEIGHT,
    BITCOIN_TESTNET_STACKS_34_BURN_HEIGHT, BITCOIN_TESTNET_STACKS_40_BURN_HEIGHT,
    BITCOIN_TESTNET_STACKS_41_BURN_HEIGHT, C32_ADDRESS_VERSION_TESTNET_MULTISIG,
    C32_ADDRESS_VERSION_TESTNET_SINGLESIG, epoch_schedule as testnet_epoch_schedule,
};
