[package]
name = "stacks-codec"
version = "0.1.0"
authors = [
    "Jude Nelson <jude@stacks.org>",
    "Aaron Blankstein <aaron@blockstack.com>",
    "Ludo Galabru <ludovic@blockstack.com>",
]
license = "GPL-3.0"
homepage = "https://github.com/stacks-network/stacks-core"
repository = "https://github.com/stacks-network/stacks-core"
description = "Binary consensus serialization codec for the Stacks blockchain"
keywords = ["stacks", "stx", "blockchain", "codec", "serialization"]
readme = "README.md"
edition = "2021"

[dependencies]
stacks-p2p = { workspace = true }
stacks-primitives = { workspace = true }
stacks-crypto = { workspace = true, default-features = false }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
const-hex = { workspace = true }

[features]
default = []
testing = ["stacks-primitives/testing"]
wasm-web = ["stacks-crypto/wasm-web", "stacks-primitives/wasm-web"]
