//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveRunChild) DeepCopyInto(out *ActiveRunChild) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveRunChild.
func (in *ActiveRunChild) DeepCopy() *ActiveRunChild {
	if in == nil {
		return nil
	}
	out := new(ActiveRunChild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorDependency) DeepCopyInto(out *ActorDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorDependency.
func (in *ActorDependency) DeepCopy() *ActorDependency {
	if in == nil {
		return nil
	}
	out := new(ActorDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorPort) DeepCopyInto(out *ActorPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorPort.
func (in *ActorPort) DeepCopy() *ActorPort {
	if in == nil {
		return nil
	}
	out := new(ActorPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorStatus) DeepCopyInto(out *ActorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorStatus.
func (in *ActorStatus) DeepCopy() *ActorStatus {
	if in == nil {
		return nil
	}
	out := new(ActorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmittedActorIdentity) DeepCopyInto(out *AdmittedActorIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmittedActorIdentity.
func (in *AdmittedActorIdentity) DeepCopy() *AdmittedActorIdentity {
	if in == nil {
		return nil
	}
	out := new(AdmittedActorIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmittedBitcoinNode) DeepCopyInto(out *AdmittedBitcoinNode) {
	*out = *in
	if in.PeerRefs != nil {
		in, out := &in.PeerRefs, &out.PeerRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmittedBitcoinNode.
func (in *AdmittedBitcoinNode) DeepCopy() *AdmittedBitcoinNode {
	if in == nil {
		return nil
	}
	out := new(AdmittedBitcoinNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmittedBurnchainTopology) DeepCopyInto(out *AdmittedBurnchainTopology) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]AdmittedBitcoinNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]BurnchainActorBinding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmittedBurnchainTopology.
func (in *AdmittedBurnchainTopology) DeepCopy() *AdmittedBurnchainTopology {
	if in == nil {
		return nil
	}
	out := new(AdmittedBurnchainTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedWorkloadOverride) DeepCopyInto(out *AdvancedWorkloadOverride) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerSecurityContext != nil {
		in, out := &in.ContainerSecurityContext, &out.ContainerSecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedWorkloadOverride.
func (in *AdvancedWorkloadOverride) DeepCopy() *AdvancedWorkloadOverride {
	if in == nil {
		return nil
	}
	out := new(AdvancedWorkloadOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdversarialEgressSpec) DeepCopyInto(out *AdversarialEgressSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdversarialEgressSpec.
func (in *AdversarialEgressSpec) DeepCopy() *AdversarialEgressSpec {
	if in == nil {
		return nil
	}
	out := new(AdversarialEgressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdversarialObserverSpec) DeepCopyInto(out *AdversarialObserverSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdversarialObserverSpec.
func (in *AdversarialObserverSpec) DeepCopy() *AdversarialObserverSpec {
	if in == nil {
		return nil
	}
	out := new(AdversarialObserverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdversarialProposalSelector) DeepCopyInto(out *AdversarialProposalSelector) {
	*out = *in
	if in.MinStacksHeight != nil {
		in, out := &in.MinStacksHeight, &out.MinStacksHeight
		*out = new(int64)
		**out = **in
	}
	if in.MaxStacksHeight != nil {
		in, out := &in.MaxStacksHeight, &out.MaxStacksHeight
		*out = new(int64)
		**out = **in
	}
	if in.EveryNth != nil {
		in, out := &in.EveryNth, &out.EveryNth
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdversarialProposalSelector.
func (in *AdversarialProposalSelector) DeepCopy() *AdversarialProposalSelector {
	if in == nil {
		return nil
	}
	out := new(AdversarialProposalSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdversarialSignerPolicy) DeepCopyInto(out *AdversarialSignerPolicy) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.Delay != nil {
		in, out := &in.Delay, &out.Delay
		*out = new(v1.Duration)
		**out = **in
	}
	in.Observer.DeepCopyInto(&out.Observer)
	out.Egress = in.Egress
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdversarialSignerPolicy.
func (in *AdversarialSignerPolicy) DeepCopy() *AdversarialSignerPolicy {
	if in == nil {
		return nil
	}
	out := new(AdversarialSignerPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttacknetRun) DeepCopyInto(out *AttacknetRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttacknetRun.
func (in *AttacknetRun) DeepCopy() *AttacknetRun {
	if in == nil {
		return nil
	}
	out := new(AttacknetRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AttacknetRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttacknetRunList) DeepCopyInto(out *AttacknetRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AttacknetRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttacknetRunList.
func (in *AttacknetRunList) DeepCopy() *AttacknetRunList {
	if in == nil {
		return nil
	}
	out := new(AttacknetRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AttacknetRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttacknetRunSpec) DeepCopyInto(out *AttacknetRunSpec) {
	*out = *in
	if in.CampaignCatalog != nil {
		in, out := &in.CampaignCatalog, &out.CampaignCatalog
		*out = make([]CampaignCatalogEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UpgradeCatalog != nil {
		in, out := &in.UpgradeCatalog, &out.UpgradeCatalog
		*out = make([]UpgradeCatalogEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Executions != nil {
		in, out := &in.Executions, &out.Executions
		*out = make([]RunExecutionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Budgets = in.Budgets
	out.StopPolicy = in.StopPolicy
	in.AttributionPolicy.DeepCopyInto(&out.AttributionPolicy)
	if in.BaselineAssertions != nil {
		in, out := &in.BaselineAssertions, &out.BaselineAssertions
		*out = new(ProtocolAssertionSetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DuringAssertions != nil {
		in, out := &in.DuringAssertions, &out.DuringAssertions
		*out = new(ProtocolAssertionSetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RecoveryAssertions != nil {
		in, out := &in.RecoveryAssertions, &out.RecoveryAssertions
		*out = new(ProtocolAssertionSetSpec)
		(*in).DeepCopyInto(*out)
	}
	out.Replay = in.Replay
	out.Resume = in.Resume
	in.Minimization.DeepCopyInto(&out.Minimization)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttacknetRunSpec.
func (in *AttacknetRunSpec) DeepCopy() *AttacknetRunSpec {
	if in == nil {
		return nil
	}
	out := new(AttacknetRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttacknetRunStatus) DeepCopyInto(out *AttacknetRunStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.ActiveChildren != nil {
		in, out := &in.ActiveChildren, &out.ActiveChildren
		*out = make([]ActiveRunChild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScheduleRef != nil {
		in, out := &in.ScheduleRef, &out.ScheduleRef
		*out = new(ScheduleReference)
		**out = **in
	}
	if in.ScheduleSummary != nil {
		in, out := &in.ScheduleSummary, &out.ScheduleSummary
		*out = new(ScheduleSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.ResolvedCampaigns != nil {
		in, out := &in.ResolvedCampaigns, &out.ResolvedCampaigns
		*out = make([]ResolvedCampaign, len(*in))
		copy(*out, *in)
	}
	if in.Decisions != nil {
		in, out := &in.Decisions, &out.Decisions
		*out = make([]apiextensionsv1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TriggerReceipts != nil {
		in, out := &in.TriggerReceipts, &out.TriggerReceipts
		*out = make([]apiextensionsv1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BudgetUsage != nil {
		in, out := &in.BudgetUsage, &out.BudgetUsage
		*out = new(BudgetUsage)
		**out = **in
	}
	if in.IdentityDivergence != nil {
		in, out := &in.IdentityDivergence, &out.IdentityDivergence
		*out = new(IdentityDivergence)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityTransitions != nil {
		in, out := &in.IdentityTransitions, &out.IdentityTransitions
		*out = make([]IdentityTransition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TerminalClassification != nil {
		in, out := &in.TerminalClassification, &out.TerminalClassification
		*out = new(TerminalClassification)
		(*in).DeepCopyInto(*out)
	}
	if in.Cleanup != nil {
		in, out := &in.Cleanup, &out.Cleanup
		*out = new(RunCleanup)
		(*in).DeepCopyInto(*out)
	}
	if in.ProtocolAssertions != nil {
		in, out := &in.ProtocolAssertions, &out.ProtocolAssertions
		*out = new(ProtocolAssertionsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttacknetRunStatus.
func (in *AttacknetRunStatus) DeepCopy() *AttacknetRunStatus {
	if in == nil {
		return nil
	}
	out := new(AttacknetRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributionPolicy) DeepCopyInto(out *AttributionPolicy) {
	*out = *in
	if in.AllowedTerminalStates != nil {
		in, out := &in.AllowedTerminalStates, &out.AllowedTerminalStates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributionPolicy.
func (in *AttributionPolicy) DeepCopy() *AttributionPolicy {
	if in == nil {
		return nil
	}
	out := new(AttributionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinNodeSpec) DeepCopyInto(out *BitcoinNodeSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	if in.PeerRefs != nil {
		in, out := &in.PeerRefs, &out.PeerRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(NamedObjectReference)
		**out = **in
	}
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Advanced != nil {
		in, out := &in.Advanced, &out.Advanced
		*out = new(AdvancedWorkloadOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinNodeSpec.
func (in *BitcoinNodeSpec) DeepCopy() *BitcoinNodeSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchCohortAssertion) DeepCopyInto(out *BranchCohortAssertion) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StableFor != nil {
		in, out := &in.StableFor, &out.StableFor
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchCohortAssertion.
func (in *BranchCohortAssertion) DeepCopy() *BranchCohortAssertion {
	if in == nil {
		return nil
	}
	out := new(BranchCohortAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetUsage) DeepCopyInto(out *BudgetUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetUsage.
func (in *BudgetUsage) DeepCopy() *BudgetUsage {
	if in == nil {
		return nil
	}
	out := new(BudgetUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainActorBinding) DeepCopyInto(out *BurnchainActorBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainActorBinding.
func (in *BurnchainActorBinding) DeepCopy() *BurnchainActorBinding {
	if in == nil {
		return nil
	}
	out := new(BurnchainActorBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainChainTipStatus) DeepCopyInto(out *BurnchainChainTipStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainChainTipStatus.
func (in *BurnchainChainTipStatus) DeepCopy() *BurnchainChainTipStatus {
	if in == nil {
		return nil
	}
	out := new(BurnchainChainTipStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainDestinationSpec) DeepCopyInto(out *BurnchainDestinationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainDestinationSpec.
func (in *BurnchainDestinationSpec) DeepCopy() *BurnchainDestinationSpec {
	if in == nil {
		return nil
	}
	out := new(BurnchainDestinationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainEpochBoundary) DeepCopyInto(out *BurnchainEpochBoundary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainEpochBoundary.
func (in *BurnchainEpochBoundary) DeepCopy() *BurnchainEpochBoundary {
	if in == nil {
		return nil
	}
	out := new(BurnchainEpochBoundary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainFlashRequest) DeepCopyInto(out *BurnchainFlashRequest) {
	*out = *in
	out.Interval = in.Interval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainFlashRequest.
func (in *BurnchainFlashRequest) DeepCopy() *BurnchainFlashRequest {
	if in == nil {
		return nil
	}
	out := new(BurnchainFlashRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainPeerStatus) DeepCopyInto(out *BurnchainPeerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainPeerStatus.
func (in *BurnchainPeerStatus) DeepCopy() *BurnchainPeerStatus {
	if in == nil {
		return nil
	}
	out := new(BurnchainPeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainPolicy) DeepCopyInto(out *BurnchainPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainPolicy.
func (in *BurnchainPolicy) DeepCopy() *BurnchainPolicy {
	if in == nil {
		return nil
	}
	out := new(BurnchainPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BurnchainPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainPolicyList) DeepCopyInto(out *BurnchainPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BurnchainPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainPolicyList.
func (in *BurnchainPolicyList) DeepCopy() *BurnchainPolicyList {
	if in == nil {
		return nil
	}
	out := new(BurnchainPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BurnchainPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainPolicySpec) DeepCopyInto(out *BurnchainPolicySpec) {
	*out = *in
	if in.ReserveOutputs != nil {
		in, out := &in.ReserveOutputs, &out.ReserveOutputs
		*out = new(int32)
		**out = **in
	}
	out.Cadence = in.Cadence
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]BurnchainDestinationSpec, len(*in))
		copy(*out, *in)
	}
	if in.Flash != nil {
		in, out := &in.Flash, &out.Flash
		*out = new(BurnchainFlashRequest)
		**out = **in
	}
	in.RPC.DeepCopyInto(&out.RPC)
	if in.ProtocolSchedule != nil {
		in, out := &in.ProtocolSchedule, &out.ProtocolSchedule
		*out = new(BurnchainProtocolSchedule)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainPolicySpec.
func (in *BurnchainPolicySpec) DeepCopy() *BurnchainPolicySpec {
	if in == nil {
		return nil
	}
	out := new(BurnchainPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainPolicyStatus) DeepCopyInto(out *BurnchainPolicyStatus) {
	*out = *in
	if in.ObservedChainTips != nil {
		in, out := &in.ObservedChainTips, &out.ObservedChainTips
		*out = make([]BurnchainChainTipStatus, len(*in))
		copy(*out, *in)
	}
	if in.ObservedPeers != nil {
		in, out := &in.ObservedPeers, &out.ObservedPeers
		*out = make([]BurnchainPeerStatus, len(*in))
		copy(*out, *in)
	}
	if in.BitcoinObservationAt != nil {
		in, out := &in.BitcoinObservationAt, &out.BitcoinObservationAt
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessAt != nil {
		in, out := &in.LastSuccessAt, &out.LastSuccessAt
		*out = (*in).DeepCopy()
	}
	if in.LastAttemptAt != nil {
		in, out := &in.LastAttemptAt, &out.LastAttemptAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainPolicyStatus.
func (in *BurnchainPolicyStatus) DeepCopy() *BurnchainPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(BurnchainPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainProtocolSchedule) DeepCopyInto(out *BurnchainProtocolSchedule) {
	*out = *in
	if in.Epochs != nil {
		in, out := &in.Epochs, &out.Epochs
		*out = make([]BurnchainEpochBoundary, len(*in))
		copy(*out, *in)
	}
	if in.RewardCycle != nil {
		in, out := &in.RewardCycle, &out.RewardCycle
		*out = new(BurnchainRewardCycleSchedule)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainProtocolSchedule.
func (in *BurnchainProtocolSchedule) DeepCopy() *BurnchainProtocolSchedule {
	if in == nil {
		return nil
	}
	out := new(BurnchainProtocolSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainRPCSpec) DeepCopyInto(out *BurnchainRPCSpec) {
	*out = *in
	out.Timeout = in.Timeout
	out.MinimumBackoff = in.MinimumBackoff
	out.MaximumBackoff = in.MaximumBackoff
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainRPCSpec.
func (in *BurnchainRPCSpec) DeepCopy() *BurnchainRPCSpec {
	if in == nil {
		return nil
	}
	out := new(BurnchainRPCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainReorgFaultSpec) DeepCopyInto(out *BurnchainReorgFaultSpec) {
	*out = *in
	out.ReplacementInterval = in.ReplacementInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainReorgFaultSpec.
func (in *BurnchainReorgFaultSpec) DeepCopy() *BurnchainReorgFaultSpec {
	if in == nil {
		return nil
	}
	out := new(BurnchainReorgFaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainRewardCycleSchedule) DeepCopyInto(out *BurnchainRewardCycleSchedule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainRewardCycleSchedule.
func (in *BurnchainRewardCycleSchedule) DeepCopy() *BurnchainRewardCycleSchedule {
	if in == nil {
		return nil
	}
	out := new(BurnchainRewardCycleSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainTopologySpec) DeepCopyInto(out *BurnchainTopologySpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]BitcoinNodeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.PolicyRef = in.PolicyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainTopologySpec.
func (in *BurnchainTopologySpec) DeepCopy() *BurnchainTopologySpec {
	if in == nil {
		return nil
	}
	out := new(BurnchainTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CampaignAdmission) DeepCopyInto(out *CampaignAdmission) {
	*out = *in
	in.NetworkInventory.DeepCopyInto(&out.NetworkInventory)
	in.AdmittedAt.DeepCopyInto(&out.AdmittedAt)
	if in.SignerSetRewardCycle != nil {
		in, out := &in.SignerSetRewardCycle, &out.SignerSetRewardCycle
		*out = new(int64)
		**out = **in
	}
	if in.SignerSetTotalWeight != nil {
		in, out := &in.SignerSetTotalWeight, &out.SignerSetTotalWeight
		*out = new(int64)
		**out = **in
	}
	if in.SignerWeightsByActor != nil {
		in, out := &in.SignerWeightsByActor, &out.SignerWeightsByActor
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AggregateImpact != nil {
		in, out := &in.AggregateImpact, &out.AggregateImpact
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CampaignAdmission.
func (in *CampaignAdmission) DeepCopy() *CampaignAdmission {
	if in == nil {
		return nil
	}
	out := new(CampaignAdmission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CampaignAssertion) DeepCopyInto(out *CampaignAssertion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CampaignAssertion.
func (in *CampaignAssertion) DeepCopy() *CampaignAssertion {
	if in == nil {
		return nil
	}
	out := new(CampaignAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CampaignCatalogEntry) DeepCopyInto(out *CampaignCatalogEntry) {
	*out = *in
	if in.ExpectedGeneration != nil {
		in, out := &in.ExpectedGeneration, &out.ExpectedGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CampaignCatalogEntry.
func (in *CampaignCatalogEntry) DeepCopy() *CampaignCatalogEntry {
	if in == nil {
		return nil
	}
	out := new(CampaignCatalogEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChainProgressAssertion) DeepCopyInto(out *ChainProgressAssertion) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Window = in.Window
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChainProgressAssertion.
func (in *ChainProgressAssertion) DeepCopy() *ChainProgressAssertion {
	if in == nil {
		return nil
	}
	out := new(ChainProgressAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosReference) DeepCopyInto(out *ChaosReference) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.InjectedAt != nil {
		in, out := &in.InjectedAt, &out.InjectedAt
		*out = (*in).DeepCopy()
	}
	if in.RecoveryContract != nil {
		in, out := &in.RecoveryContract, &out.RecoveryContract
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosReference.
func (in *ChaosReference) DeepCopy() *ChaosReference {
	if in == nil {
		return nil
	}
	out := new(ChaosReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanupEvidence) DeepCopyInto(out *CleanupEvidence) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanupEvidence.
func (in *CleanupEvidence) DeepCopy() *CleanupEvidence {
	if in == nil {
		return nil
	}
	out := new(CleanupEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CohortAgreementAssertion) DeepCopyInto(out *CohortAgreementAssertion) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConvergenceWindow != nil {
		in, out := &in.ConvergenceWindow, &out.ConvergenceWindow
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CohortAgreementAssertion.
func (in *CohortAgreementAssertion) DeepCopy() *CohortAgreementAssertion {
	if in == nil {
		return nil
	}
	out := new(CohortAgreementAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigObjectRef) DeepCopyInto(out *ConfigObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigObjectRef.
func (in *ConfigObjectRef) DeepCopy() *ConfigObjectRef {
	if in == nil {
		return nil
	}
	out := new(ConfigObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSource) DeepCopyInto(out *ConfigSource) {
	*out = *in
	if in.Generated != nil {
		in, out := &in.Generated, &out.Generated
		*out = new(GeneratedConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigObjectRef)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(ConfigObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSource.
func (in *ConfigSource) DeepCopy() *ConfigSource {
	if in == nil {
		return nil
	}
	out := new(ConfigSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultActionSpec) DeepCopyInto(out *FaultActionSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	in.Fault.DeepCopyInto(&out.Fault)
	if in.EffectAssertions != nil {
		in, out := &in.EffectAssertions, &out.EffectAssertions
		*out = make([]CampaignAssertion, len(*in))
		copy(*out, *in)
	}
	if in.RecoveryAssertions != nil {
		in, out := &in.RecoveryAssertions, &out.RecoveryAssertions
		*out = make([]CampaignAssertion, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultActionSpec.
func (in *FaultActionSpec) DeepCopy() *FaultActionSpec {
	if in == nil {
		return nil
	}
	out := new(FaultActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultActionStatus) DeepCopyInto(out *FaultActionStatus) {
	*out = *in
	if in.ResolvedTargets != nil {
		in, out := &in.ResolvedTargets, &out.ResolvedTargets
		*out = make([]ResolvedTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CapabilityEvidence != nil {
		in, out := &in.CapabilityEvidence, &out.CapabilityEvidence
		*out = make([]apiextensionsv1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Mutation != nil {
		in, out := &in.Mutation, &out.Mutation
		*out = new(ChaosReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ActualInjection != nil {
		in, out := &in.ActualInjection, &out.ActualInjection
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.EffectResults != nil {
		in, out := &in.EffectResults, &out.EffectResults
		*out = make([]apiextensionsv1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RecoveryResults != nil {
		in, out := &in.RecoveryResults, &out.RecoveryResults
		*out = make([]apiextensionsv1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultActionStatus.
func (in *FaultActionStatus) DeepCopy() *FaultActionStatus {
	if in == nil {
		return nil
	}
	out := new(FaultActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultCampaign) DeepCopyInto(out *FaultCampaign) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultCampaign.
func (in *FaultCampaign) DeepCopy() *FaultCampaign {
	if in == nil {
		return nil
	}
	out := new(FaultCampaign)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FaultCampaign) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultCampaignList) DeepCopyInto(out *FaultCampaignList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FaultCampaign, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultCampaignList.
func (in *FaultCampaignList) DeepCopy() *FaultCampaignList {
	if in == nil {
		return nil
	}
	out := new(FaultCampaignList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FaultCampaignList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultCampaignSpec) DeepCopyInto(out *FaultCampaignSpec) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]FaultStageSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Safety = in.Safety
	if in.EffectAssertions != nil {
		in, out := &in.EffectAssertions, &out.EffectAssertions
		*out = make([]CampaignAssertion, len(*in))
		copy(*out, *in)
	}
	if in.RecoveryAssertions != nil {
		in, out := &in.RecoveryAssertions, &out.RecoveryAssertions
		*out = make([]CampaignAssertion, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultCampaignSpec.
func (in *FaultCampaignSpec) DeepCopy() *FaultCampaignSpec {
	if in == nil {
		return nil
	}
	out := new(FaultCampaignSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultCampaignStatus) DeepCopyInto(out *FaultCampaignStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Admission != nil {
		in, out := &in.Admission, &out.Admission
		*out = new(CampaignAdmission)
		(*in).DeepCopyInto(*out)
	}
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]FaultStageStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveStageIDs != nil {
		in, out := &in.ActiveStageIDs, &out.ActiveStageIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProbeArtifacts != nil {
		in, out := &in.ProbeArtifacts, &out.ProbeArtifacts
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Cleanup != nil {
		in, out := &in.Cleanup, &out.Cleanup
		*out = new(CleanupEvidence)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityDivergence != nil {
		in, out := &in.IdentityDivergence, &out.IdentityDivergence
		*out = new(IdentityDivergence)
		(*in).DeepCopyInto(*out)
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultCampaignStatus.
func (in *FaultCampaignStatus) DeepCopy() *FaultCampaignStatus {
	if in == nil {
		return nil
	}
	out := new(FaultCampaignStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultSafety) DeepCopyInto(out *FaultSafety) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultSafety.
func (in *FaultSafety) DeepCopy() *FaultSafety {
	if in == nil {
		return nil
	}
	out := new(FaultSafety)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultSpec) DeepCopyInto(out *FaultSpec) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(intstr.IntOrString)
		**out = **in
	}
	out.Duration = in.Duration
	in.Parameters.DeepCopyInto(&out.Parameters)
	if in.BurnchainReorg != nil {
		in, out := &in.BurnchainReorg, &out.BurnchainReorg
		*out = new(BurnchainReorgFaultSpec)
		**out = **in
	}
	if in.SignerBehavior != nil {
		in, out := &in.SignerBehavior, &out.SignerBehavior
		*out = new(SignerBehaviorFaultSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultSpec.
func (in *FaultSpec) DeepCopy() *FaultSpec {
	if in == nil {
		return nil
	}
	out := new(FaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultStageSpec) DeepCopyInto(out *FaultStageSpec) {
	*out = *in
	in.Trigger.DeepCopyInto(&out.Trigger)
	out.MaxStartSkew = in.MaxStartSkew
	if in.Faults != nil {
		in, out := &in.Faults, &out.Faults
		*out = make([]FaultActionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EffectAssertions != nil {
		in, out := &in.EffectAssertions, &out.EffectAssertions
		*out = make([]CampaignAssertion, len(*in))
		copy(*out, *in)
	}
	if in.RecoveryAssertions != nil {
		in, out := &in.RecoveryAssertions, &out.RecoveryAssertions
		*out = make([]CampaignAssertion, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultStageSpec.
func (in *FaultStageSpec) DeepCopy() *FaultStageSpec {
	if in == nil {
		return nil
	}
	out := new(FaultStageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultStageStatus) DeepCopyInto(out *FaultStageStatus) {
	*out = *in
	if in.TriggerReceipt != nil {
		in, out := &in.TriggerReceipt, &out.TriggerReceipt
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.EligibleAt != nil {
		in, out := &in.EligibleAt, &out.EligibleAt
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.ObservedStartSkew != nil {
		in, out := &in.ObservedStartSkew, &out.ObservedStartSkew
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]FaultActionStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EffectResults != nil {
		in, out := &in.EffectResults, &out.EffectResults
		*out = make([]apiextensionsv1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RecoveryResults != nil {
		in, out := &in.RecoveryResults, &out.RecoveryResults
		*out = make([]apiextensionsv1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultStageStatus.
func (in *FaultStageStatus) DeepCopy() *FaultStageStatus {
	if in == nil {
		return nil
	}
	out := new(FaultStageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultTarget) DeepCopyInto(out *FaultTarget) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultTarget.
func (in *FaultTarget) DeepCopy() *FaultTarget {
	if in == nil {
		return nil
	}
	out := new(FaultTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratedConfigSpec) DeepCopyInto(out *GeneratedConfigSpec) {
	*out = *in
	if in.BootstrapPeers != nil {
		in, out := &in.BootstrapPeers, &out.BootstrapPeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratedConfigSpec.
func (in *GeneratedConfigSpec) DeepCopy() *GeneratedConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GeneratedConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisBalanceSpec) DeepCopyInto(out *GenesisBalanceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisBalanceSpec.
func (in *GenesisBalanceSpec) DeepCopy() *GenesisBalanceSpec {
	if in == nil {
		return nil
	}
	out := new(GenesisBalanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityDifference) DeepCopyInto(out *IdentityDifference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityDifference.
func (in *IdentityDifference) DeepCopy() *IdentityDifference {
	if in == nil {
		return nil
	}
	out := new(IdentityDifference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityDivergence) DeepCopyInto(out *IdentityDivergence) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.Differences != nil {
		in, out := &in.Differences, &out.Differences
		*out = make([]IdentityDifference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityDivergence.
func (in *IdentityDivergence) DeepCopy() *IdentityDivergence {
	if in == nil {
		return nil
	}
	out := new(IdentityDivergence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityTransition) DeepCopyInto(out *IdentityTransition) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityTransition.
func (in *IdentityTransition) DeepCopy() *IdentityTransition {
	if in == nil {
		return nil
	}
	out := new(IdentityTransition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinimizationSpec) DeepCopyInto(out *MinimizationSpec) {
	*out = *in
	if in.Retained != nil {
		in, out := &in.Retained, &out.Retained
		*out = make([]RetainedExecution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinimizationSpec.
func (in *MinimizationSpec) DeepCopy() *MinimizationSpec {
	if in == nil {
		return nil
	}
	out := new(MinimizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedObjectReference) DeepCopyInto(out *NamedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedObjectReference.
func (in *NamedObjectReference) DeepCopy() *NamedObjectReference {
	if in == nil {
		return nil
	}
	out := new(NamedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDefaults) DeepCopyInto(out *NetworkDefaults) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.BootstrapPeers != nil {
		in, out := &in.BootstrapPeers, &out.BootstrapPeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Workload.DeepCopyInto(&out.Workload)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDefaults.
func (in *NetworkDefaults) DeepCopy() *NetworkDefaults {
	if in == nil {
		return nil
	}
	out := new(NetworkDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInventory) DeepCopyInto(out *NetworkInventory) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.BurnchainTopology != nil {
		in, out := &in.BurnchainTopology, &out.BurnchainTopology
		*out = new(AdmittedBurnchainTopology)
		(*in).DeepCopyInto(*out)
	}
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]AdmittedActorIdentity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInventory.
func (in *NetworkInventory) DeepCopy() *NetworkInventory {
	if in == nil {
		return nil
	}
	out := new(NetworkInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservationTriggerSpec) DeepCopyInto(out *ObservationTriggerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservationTriggerSpec.
func (in *ObservationTriggerSpec) DeepCopy() *ObservationTriggerSpec {
	if in == nil {
		return nil
	}
	out := new(ObservationTriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoX5GenesisSpec) DeepCopyInto(out *PoX5GenesisSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoX5GenesisSpec.
func (in *PoX5GenesisSpec) DeepCopy() *PoX5GenesisSpec {
	if in == nil {
		return nil
	}
	out := new(PoX5GenesisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbePort) DeepCopyInto(out *ProbePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbePort.
func (in *ProbePort) DeepCopy() *ProbePort {
	if in == nil {
		return nil
	}
	out := new(ProbePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeService) DeepCopyInto(out *ProbeService) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ProbePort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeService.
func (in *ProbeService) DeepCopy() *ProbeService {
	if in == nil {
		return nil
	}
	out := new(ProbeService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeSpec) DeepCopyInto(out *ProbeSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalServices != nil {
		in, out := &in.AdditionalServices, &out.AdditionalServices
		*out = make([]ProbeService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeSpec.
func (in *ProbeSpec) DeepCopy() *ProbeSpec {
	if in == nil {
		return nil
	}
	out := new(ProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProposalOutcomeVisibilityAssertion) DeepCopyInto(out *ProposalOutcomeVisibilityAssertion) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Window = in.Window
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProposalOutcomeVisibilityAssertion.
func (in *ProposalOutcomeVisibilityAssertion) DeepCopy() *ProposalOutcomeVisibilityAssertion {
	if in == nil {
		return nil
	}
	out := new(ProposalOutcomeVisibilityAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolAssertionResult) DeepCopyInto(out *ProtocolAssertionResult) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	in.Evidence.DeepCopyInto(&out.Evidence)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolAssertionResult.
func (in *ProtocolAssertionResult) DeepCopy() *ProtocolAssertionResult {
	if in == nil {
		return nil
	}
	out := new(ProtocolAssertionResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolAssertionSetSpec) DeepCopyInto(out *ProtocolAssertionSetSpec) {
	*out = *in
	out.Timeout = in.Timeout
	if in.Assertions != nil {
		in, out := &in.Assertions, &out.Assertions
		*out = make([]ProtocolAssertionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolAssertionSetSpec.
func (in *ProtocolAssertionSetSpec) DeepCopy() *ProtocolAssertionSetSpec {
	if in == nil {
		return nil
	}
	out := new(ProtocolAssertionSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolAssertionSetStatus) DeepCopyInto(out *ProtocolAssertionSetStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]ProtocolAssertionResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolAssertionSetStatus.
func (in *ProtocolAssertionSetStatus) DeepCopy() *ProtocolAssertionSetStatus {
	if in == nil {
		return nil
	}
	out := new(ProtocolAssertionSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolAssertionSpec) DeepCopyInto(out *ProtocolAssertionSpec) {
	*out = *in
	if in.ChainProgress != nil {
		in, out := &in.ChainProgress, &out.ChainProgress
		*out = new(ChainProgressAssertion)
		(*in).DeepCopyInto(*out)
	}
	if in.CohortAgreement != nil {
		in, out := &in.CohortAgreement, &out.CohortAgreement
		*out = new(CohortAgreementAssertion)
		(*in).DeepCopyInto(*out)
	}
	if in.SignerRegistration != nil {
		in, out := &in.SignerRegistration, &out.SignerRegistration
		*out = new(SignerRegistrationAssertion)
		(*in).DeepCopyInto(*out)
	}
	if in.SignerStateFreshness != nil {
		in, out := &in.SignerStateFreshness, &out.SignerStateFreshness
		*out = new(SignerStateFreshnessAssertion)
		(*in).DeepCopyInto(*out)
	}
	if in.ProposalOutcomeVisibility != nil {
		in, out := &in.ProposalOutcomeVisibility, &out.ProposalOutcomeVisibility
		*out = new(ProposalOutcomeVisibilityAssertion)
		(*in).DeepCopyInto(*out)
	}
	if in.TelemetryCompleteness != nil {
		in, out := &in.TelemetryCompleteness, &out.TelemetryCompleteness
		*out = new(TelemetryCompletenessAssertion)
		(*in).DeepCopyInto(*out)
	}
	if in.BitcoinBranchCohort != nil {
		in, out := &in.BitcoinBranchCohort, &out.BitcoinBranchCohort
		*out = new(BranchCohortAssertion)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksBurnchainCohort != nil {
		in, out := &in.StacksBurnchainCohort, &out.StacksBurnchainCohort
		*out = new(BranchCohortAssertion)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolAssertionSpec.
func (in *ProtocolAssertionSpec) DeepCopy() *ProtocolAssertionSpec {
	if in == nil {
		return nil
	}
	out := new(ProtocolAssertionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolAssertionsStatus) DeepCopyInto(out *ProtocolAssertionsStatus) {
	*out = *in
	if in.Baseline != nil {
		in, out := &in.Baseline, &out.Baseline
		*out = new(ProtocolAssertionSetStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.During != nil {
		in, out := &in.During, &out.During
		*out = new(ProtocolAssertionSetStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Recovery != nil {
		in, out := &in.Recovery, &out.Recovery
		*out = new(ProtocolAssertionSetStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolAssertionsStatus.
func (in *ProtocolAssertionsStatus) DeepCopy() *ProtocolAssertionsStatus {
	if in == nil {
		return nil
	}
	out := new(ProtocolAssertionsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawActorSpec) DeepCopyInto(out *RawActorSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ActorPort, len(*in))
		copy(*out, *in)
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]ActorDependency, len(*in))
		copy(*out, *in)
	}
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Advanced != nil {
		in, out := &in.Advanced, &out.Advanced
		*out = new(AdvancedWorkloadOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawActorSpec.
func (in *RawActorSpec) DeepCopy() *RawActorSpec {
	if in == nil {
		return nil
	}
	out := new(RawActorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplaySpec) DeepCopyInto(out *ReplaySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplaySpec.
func (in *ReplaySpec) DeepCopy() *ReplaySpec {
	if in == nil {
		return nil
	}
	out := new(ReplaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedCampaign) DeepCopyInto(out *ResolvedCampaign) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedCampaign.
func (in *ResolvedCampaign) DeepCopy() *ResolvedCampaign {
	if in == nil {
		return nil
	}
	out := new(ResolvedCampaign)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedTarget) DeepCopyInto(out *ResolvedTarget) {
	*out = *in
	if in.RequestedImage != nil {
		in, out := &in.RequestedImage, &out.RequestedImage
		*out = new(string)
		**out = **in
	}
	if in.ResolvedImageID != nil {
		in, out := &in.ResolvedImageID, &out.ResolvedImageID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedTarget.
func (in *ResolvedTarget) DeepCopy() *ResolvedTarget {
	if in == nil {
		return nil
	}
	out := new(ResolvedTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResumeSpec) DeepCopyInto(out *ResumeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResumeSpec.
func (in *ResumeSpec) DeepCopy() *ResumeSpec {
	if in == nil {
		return nil
	}
	out := new(ResumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetainedExecution) DeepCopyInto(out *RetainedExecution) {
	*out = *in
	if in.RemovedStages != nil {
		in, out := &in.RemovedStages, &out.RemovedStages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemovedActions != nil {
		in, out := &in.RemovedActions, &out.RemovedActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemovedTargets != nil {
		in, out := &in.RemovedTargets, &out.RemovedTargets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemovedParameters != nil {
		in, out := &in.RemovedParameters, &out.RemovedParameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetainedExecution.
func (in *RetainedExecution) DeepCopy() *RetainedExecution {
	if in == nil {
		return nil
	}
	out := new(RetainedExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunBudgets) DeepCopyInto(out *RunBudgets) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunBudgets.
func (in *RunBudgets) DeepCopy() *RunBudgets {
	if in == nil {
		return nil
	}
	out := new(RunBudgets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunCleanup) DeepCopyInto(out *RunCleanup) {
	*out = *in
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunCleanup.
func (in *RunCleanup) DeepCopy() *RunCleanup {
	if in == nil {
		return nil
	}
	out := new(RunCleanup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunExecutionDependency) DeepCopyInto(out *RunExecutionDependency) {
	*out = *in
	out.Delay = in.Delay
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunExecutionDependency.
func (in *RunExecutionDependency) DeepCopy() *RunExecutionDependency {
	if in == nil {
		return nil
	}
	out := new(RunExecutionDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunExecutionSpec) DeepCopyInto(out *RunExecutionSpec) {
	*out = *in
	in.Trigger.DeepCopyInto(&out.Trigger)
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]RunExecutionDependency, len(*in))
		copy(*out, *in)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunExecutionSpec.
func (in *RunExecutionSpec) DeepCopy() *RunExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(RunExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunTriggerSpec) DeepCopyInto(out *RunTriggerSpec) {
	*out = *in
	if in.AfterRunStart != nil {
		in, out := &in.AfterRunStart, &out.AfterRunStart
		*out = new(v1.Duration)
		**out = **in
	}
	if in.BurnHeight != nil {
		in, out := &in.BurnHeight, &out.BurnHeight
		*out = new(int64)
		**out = **in
	}
	if in.StacksHeight != nil {
		in, out := &in.StacksHeight, &out.StacksHeight
		*out = new(int64)
		**out = **in
	}
	if in.Observation != nil {
		in, out := &in.Observation, &out.Observation
		*out = new(ObservationTriggerSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunTriggerSpec.
func (in *RunTriggerSpec) DeepCopy() *RunTriggerSpec {
	if in == nil {
		return nil
	}
	out := new(RunTriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleReference) DeepCopyInto(out *ScheduleReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleReference.
func (in *ScheduleReference) DeepCopy() *ScheduleReference {
	if in == nil {
		return nil
	}
	out := new(ScheduleReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleSummary) DeepCopyInto(out *ScheduleSummary) {
	*out = *in
	if in.SignerSetRewardCycle != nil {
		in, out := &in.SignerSetRewardCycle, &out.SignerSetRewardCycle
		*out = new(int64)
		**out = **in
	}
	if in.SignerSetTotalWeight != nil {
		in, out := &in.SignerSetTotalWeight, &out.SignerSetTotalWeight
		*out = new(int64)
		**out = **in
	}
	in.NetworkInventory.DeepCopyInto(&out.NetworkInventory)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleSummary.
func (in *ScheduleSummary) DeepCopy() *ScheduleSummary {
	if in == nil {
		return nil
	}
	out := new(ScheduleSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignerBehaviorFaultSpec) DeepCopyInto(out *SignerBehaviorFaultSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignerBehaviorFaultSpec.
func (in *SignerBehaviorFaultSpec) DeepCopy() *SignerBehaviorFaultSpec {
	if in == nil {
		return nil
	}
	out := new(SignerBehaviorFaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignerEnrollmentSecretRef) DeepCopyInto(out *SignerEnrollmentSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignerEnrollmentSecretRef.
func (in *SignerEnrollmentSecretRef) DeepCopy() *SignerEnrollmentSecretRef {
	if in == nil {
		return nil
	}
	out := new(SignerEnrollmentSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignerEnrollmentSpec) DeepCopyInto(out *SignerEnrollmentSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Advanced != nil {
		in, out := &in.Advanced, &out.Advanced
		*out = new(AdvancedWorkloadOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignerEnrollmentSpec.
func (in *SignerEnrollmentSpec) DeepCopy() *SignerEnrollmentSpec {
	if in == nil {
		return nil
	}
	out := new(SignerEnrollmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignerMemberSpec) DeepCopyInto(out *SignerMemberSpec) {
	*out = *in
	in.SignerConfig.DeepCopyInto(&out.SignerConfig)
	in.NodeConfig.DeepCopyInto(&out.NodeConfig)
	if in.SignerWorkload != nil {
		in, out := &in.SignerWorkload, &out.SignerWorkload
		*out = new(WorkloadPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeWorkload != nil {
		in, out := &in.NodeWorkload, &out.NodeWorkload
		*out = new(WorkloadPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.SignerAdvanced != nil {
		in, out := &in.SignerAdvanced, &out.SignerAdvanced
		*out = new(AdvancedWorkloadOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeAdvanced != nil {
		in, out := &in.NodeAdvanced, &out.NodeAdvanced
		*out = new(AdvancedWorkloadOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.Adversarial != nil {
		in, out := &in.Adversarial, &out.Adversarial
		*out = new(AdversarialSignerPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignerMemberSpec.
func (in *SignerMemberSpec) DeepCopy() *SignerMemberSpec {
	if in == nil {
		return nil
	}
	out := new(SignerMemberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignerRegistrationAssertion) DeepCopyInto(out *SignerRegistrationAssertion) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignerRegistrationAssertion.
func (in *SignerRegistrationAssertion) DeepCopy() *SignerRegistrationAssertion {
	if in == nil {
		return nil
	}
	out := new(SignerRegistrationAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignerSetSpec) DeepCopyInto(out *SignerSetSpec) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]SignerMemberSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignerSetSpec.
func (in *SignerSetSpec) DeepCopy() *SignerSetSpec {
	if in == nil {
		return nil
	}
	out := new(SignerSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignerStateFreshnessAssertion) DeepCopyInto(out *SignerStateFreshnessAssertion) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.MaximumAge = in.MaximumAge
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignerStateFreshnessAssertion.
func (in *SignerStateFreshnessAssertion) DeepCopy() *SignerStateFreshnessAssertion {
	if in == nil {
		return nil
	}
	out := new(SignerStateFreshnessAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksGenesisSpec) DeepCopyInto(out *StacksGenesisSpec) {
	*out = *in
	if in.PoX5 != nil {
		in, out := &in.PoX5, &out.PoX5
		*out = new(PoX5GenesisSpec)
		**out = **in
	}
	if in.Balances != nil {
		in, out := &in.Balances, &out.Balances
		*out = make([]GenesisBalanceSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksGenesisSpec.
func (in *StacksGenesisSpec) DeepCopy() *StacksGenesisSpec {
	if in == nil {
		return nil
	}
	out := new(StacksGenesisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetwork) DeepCopyInto(out *StacksNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetwork.
func (in *StacksNetwork) DeepCopy() *StacksNetwork {
	if in == nil {
		return nil
	}
	out := new(StacksNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkList) DeepCopyInto(out *StacksNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkList.
func (in *StacksNetworkList) DeepCopy() *StacksNetworkList {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkSpec) DeepCopyInto(out *StacksNetworkSpec) {
	*out = *in
	in.Defaults.DeepCopyInto(&out.Defaults)
	if in.Genesis != nil {
		in, out := &in.Genesis, &out.Genesis
		*out = new(StacksGenesisSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Burnchain.DeepCopyInto(&out.Burnchain)
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]StacksNodeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SignerSets != nil {
		in, out := &in.SignerSets, &out.SignerSets
		*out = make([]SignerSetSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enrollment != nil {
		in, out := &in.Enrollment, &out.Enrollment
		*out = new(SignerEnrollmentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RawActors != nil {
		in, out := &in.RawActors, &out.RawActors
		*out = make([]RawActorSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetrySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Probe != nil {
		in, out := &in.Probe, &out.Probe
		*out = new(ProbeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SuspensionGrace != nil {
		in, out := &in.SuspensionGrace, &out.SuspensionGrace
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkSpec.
func (in *StacksNetworkSpec) DeepCopy() *StacksNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkStatus) DeepCopyInto(out *StacksNetworkStatus) {
	*out = *in
	if in.InventoryObservedAt != nil {
		in, out := &in.InventoryObservedAt, &out.InventoryObservedAt
		*out = (*in).DeepCopy()
	}
	if in.BurnchainTopology != nil {
		in, out := &in.BurnchainTopology, &out.BurnchainTopology
		*out = new(AdmittedBurnchainTopology)
		(*in).DeepCopyInto(*out)
	}
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]ActorStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkStatus.
func (in *StacksNetworkStatus) DeepCopy() *StacksNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNodeSpec) DeepCopyInto(out *StacksNodeSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Advanced != nil {
		in, out := &in.Advanced, &out.Advanced
		*out = new(AdvancedWorkloadOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNodeSpec.
func (in *StacksNodeSpec) DeepCopy() *StacksNodeSpec {
	if in == nil {
		return nil
	}
	out := new(StacksNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageDependency) DeepCopyInto(out *StageDependency) {
	*out = *in
	out.Delay = in.Delay
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageDependency.
func (in *StageDependency) DeepCopy() *StageDependency {
	if in == nil {
		return nil
	}
	out := new(StageDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageTriggerSpec) DeepCopyInto(out *StageTriggerSpec) {
	*out = *in
	if in.AfterCampaignStart != nil {
		in, out := &in.AfterCampaignStart, &out.AfterCampaignStart
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AfterStage != nil {
		in, out := &in.AfterStage, &out.AfterStage
		*out = new(StageDependency)
		**out = **in
	}
	if in.BurnHeight != nil {
		in, out := &in.BurnHeight, &out.BurnHeight
		*out = new(int64)
		**out = **in
	}
	if in.StacksHeight != nil {
		in, out := &in.StacksHeight, &out.StacksHeight
		*out = new(int64)
		**out = **in
	}
	if in.Observation != nil {
		in, out := &in.Observation, &out.Observation
		*out = new(ObservationTriggerSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageTriggerSpec.
func (in *StageTriggerSpec) DeepCopy() *StageTriggerSpec {
	if in == nil {
		return nil
	}
	out := new(StageTriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StopPolicy) DeepCopyInto(out *StopPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StopPolicy.
func (in *StopPolicy) DeepCopy() *StopPolicy {
	if in == nil {
		return nil
	}
	out := new(StopPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]corev1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryCompletenessAssertion) DeepCopyInto(out *TelemetryCompletenessAssertion) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryCompletenessAssertion.
func (in *TelemetryCompletenessAssertion) DeepCopy() *TelemetryCompletenessAssertion {
	if in == nil {
		return nil
	}
	out := new(TelemetryCompletenessAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryExporterServiceReference) DeepCopyInto(out *TelemetryExporterServiceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryExporterServiceReference.
func (in *TelemetryExporterServiceReference) DeepCopy() *TelemetryExporterServiceReference {
	if in == nil {
		return nil
	}
	out := new(TelemetryExporterServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetrySpec) DeepCopyInto(out *TelemetrySpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ExporterServiceRef != nil {
		in, out := &in.ExporterServiceRef, &out.ExporterServiceRef
		*out = new(TelemetryExporterServiceReference)
		**out = **in
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetrySpec.
func (in *TelemetrySpec) DeepCopy() *TelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(TelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerminalClassification) DeepCopyInto(out *TerminalClassification) {
	*out = *in
	if in.Observations != nil {
		in, out := &in.Observations, &out.Observations
		*out = make([]apiextensionsv1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerminalClassification.
func (in *TerminalClassification) DeepCopy() *TerminalClassification {
	if in == nil {
		return nil
	}
	out := new(TerminalClassification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeAssignment) DeepCopyInto(out *UpgradeAssignment) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConfigSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeAssignment.
func (in *UpgradeAssignment) DeepCopy() *UpgradeAssignment {
	if in == nil {
		return nil
	}
	out := new(UpgradeAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeCampaign) DeepCopyInto(out *UpgradeCampaign) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeCampaign.
func (in *UpgradeCampaign) DeepCopy() *UpgradeCampaign {
	if in == nil {
		return nil
	}
	out := new(UpgradeCampaign)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeCampaign) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeCampaignList) DeepCopyInto(out *UpgradeCampaignList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpgradeCampaign, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeCampaignList.
func (in *UpgradeCampaignList) DeepCopy() *UpgradeCampaignList {
	if in == nil {
		return nil
	}
	out := new(UpgradeCampaignList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeCampaignList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeCampaignSpec) DeepCopyInto(out *UpgradeCampaignSpec) {
	*out = *in
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]UpgradeProfileSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]UpgradeStageSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Safety = in.Safety
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeCampaignSpec.
func (in *UpgradeCampaignSpec) DeepCopy() *UpgradeCampaignSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeCampaignSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeCampaignStatus) DeepCopyInto(out *UpgradeCampaignStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.BaselineInventory != nil {
		in, out := &in.BaselineInventory, &out.BaselineInventory
		*out = new(NetworkInventory)
		(*in).DeepCopyInto(*out)
	}
	if in.CurrentInventory != nil {
		in, out := &in.CurrentInventory, &out.CurrentInventory
		*out = new(NetworkInventory)
		(*in).DeepCopyInto(*out)
	}
	if in.StageStartedAt != nil {
		in, out := &in.StageStartedAt, &out.StageStartedAt
		*out = (*in).DeepCopy()
	}
	if in.StageReadySince != nil {
		in, out := &in.StageReadySince, &out.StageReadySince
		*out = (*in).DeepCopy()
	}
	if in.StageAssertions != nil {
		in, out := &in.StageAssertions, &out.StageAssertions
		*out = new(ProtocolAssertionSetStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.AppliedAssignments != nil {
		in, out := &in.AppliedAssignments, &out.AppliedAssignments
		*out = make([]UpgradeAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IdentityTransitions != nil {
		in, out := &in.IdentityTransitions, &out.IdentityTransitions
		*out = make([]IdentityTransition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeCampaignStatus.
func (in *UpgradeCampaignStatus) DeepCopy() *UpgradeCampaignStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradeCampaignStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeCatalogEntry) DeepCopyInto(out *UpgradeCatalogEntry) {
	*out = *in
	if in.ExpectedGeneration != nil {
		in, out := &in.ExpectedGeneration, &out.ExpectedGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeCatalogEntry.
func (in *UpgradeCatalogEntry) DeepCopy() *UpgradeCatalogEntry {
	if in == nil {
		return nil
	}
	out := new(UpgradeCatalogEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeProfileSpec) DeepCopyInto(out *UpgradeProfileSpec) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeProfileSpec.
func (in *UpgradeProfileSpec) DeepCopy() *UpgradeProfileSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeSafetySpec) DeepCopyInto(out *UpgradeSafetySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeSafetySpec.
func (in *UpgradeSafetySpec) DeepCopy() *UpgradeSafetySpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeSafetySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeStageSpec) DeepCopyInto(out *UpgradeStageSpec) {
	*out = *in
	if in.Assignments != nil {
		in, out := &in.Assignments, &out.Assignments
		*out = make([]UpgradeAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.StableFor = in.StableFor
	out.Deadline = in.Deadline
	if in.Assertions != nil {
		in, out := &in.Assertions, &out.Assertions
		*out = new(ProtocolAssertionSetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeStageSpec.
func (in *UpgradeStageSpec) DeepCopy() *UpgradeStageSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeStageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicy) DeepCopyInto(out *WorkloadPolicy) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetrySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Probe != nil {
		in, out := &in.Probe, &out.Probe
		*out = new(ProbeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicy.
func (in *WorkloadPolicy) DeepCopy() *WorkloadPolicy {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicy)
	in.DeepCopyInto(out)
	return out
}
