{{- if and .Values.runOperator.enabled .Values.runServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hacknet.runServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hacknet.labels" . | nindent 4 }}
    app.kubernetes.io/component: run-operator
  {{- with .Values.runServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
