apiVersion: v1
kind: Service
metadata:
  name: {{ include "hacknet.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hacknet.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  selector:
    {{- include "hacknet.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
