//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveRunChild) DeepCopyInto(out *ActiveRunChild) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveRunChild.
func (in *ActiveRunChild) DeepCopy() *ActiveRunChild {
	if in == nil {
		return nil
	}
	out := new(ActiveRunChild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorConfig) DeepCopyInto(out *ActorConfig) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorConfig.
func (in *ActorConfig) DeepCopy() *ActorConfig {
	if in == nil {
		return nil
	}
	out := new(ActorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorDependency) DeepCopyInto(out *ActorDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorDependency.
func (in *ActorDependency) DeepCopy() *ActorDependency {
	if in == nil {
		return nil
	}
	out := new(ActorDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorPort) DeepCopyInto(out *ActorPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorPort.
func (in *ActorPort) DeepCopy() *ActorPort {
	if in == nil {
		return nil
	}
	out := new(ActorPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorSpec) DeepCopyInto(out *ActorSpec) {
	*out = *in
	if in.SignerIndex != nil {
		in, out := &in.SignerIndex, &out.SignerIndex
		*out = new(int32)
		**out = **in
	}
	if in.SignerWeight != nil {
		in, out := &in.SignerWeight, &out.SignerWeight
		*out = new(float64)
		**out = **in
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ActorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ActorPort, len(*in))
		copy(*out, *in)
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]ActorDependency, len(*in))
		copy(*out, *in)
	}
	if in.EgressPeers != nil {
		in, out := &in.EgressPeers, &out.EgressPeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerSecurityContext != nil {
		in, out := &in.ContainerSecurityContext, &out.ContainerSecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.RuntimePolicy != nil {
		in, out := &in.RuntimePolicy, &out.RuntimePolicy
		*out = new(RuntimePolicySpec)
		**out = **in
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetrySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Probe != nil {
		in, out := &in.Probe, &out.Probe
		*out = new(ProbeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorSpec.
func (in *ActorSpec) DeepCopy() *ActorSpec {
	if in == nil {
		return nil
	}
	out := new(ActorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorStatus) DeepCopyInto(out *ActorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorStatus.
func (in *ActorStatus) DeepCopy() *ActorStatus {
	if in == nil {
		return nil
	}
	out := new(ActorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmittedActorIdentity) DeepCopyInto(out *AdmittedActorIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmittedActorIdentity.
func (in *AdmittedActorIdentity) DeepCopy() *AdmittedActorIdentity {
	if in == nil {
		return nil
	}
	out := new(AdmittedActorIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttacknetRun) DeepCopyInto(out *AttacknetRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttacknetRun.
func (in *AttacknetRun) DeepCopy() *AttacknetRun {
	if in == nil {
		return nil
	}
	out := new(AttacknetRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AttacknetRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttacknetRunList) DeepCopyInto(out *AttacknetRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AttacknetRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttacknetRunList.
func (in *AttacknetRunList) DeepCopy() *AttacknetRunList {
	if in == nil {
		return nil
	}
	out := new(AttacknetRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AttacknetRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttacknetRunSpec) DeepCopyInto(out *AttacknetRunSpec) {
	*out = *in
	if in.CampaignCatalog != nil {
		in, out := &in.CampaignCatalog, &out.CampaignCatalog
		*out = make([]CampaignCatalogEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sequence != nil {
		in, out := &in.Sequence, &out.Sequence
		*out = make([]RunInstruction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Budgets = in.Budgets
	out.StopPolicy = in.StopPolicy
	in.AttributionPolicy.DeepCopyInto(&out.AttributionPolicy)
	out.Replay = in.Replay
	out.Resume = in.Resume
	in.Minimization.DeepCopyInto(&out.Minimization)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttacknetRunSpec.
func (in *AttacknetRunSpec) DeepCopy() *AttacknetRunSpec {
	if in == nil {
		return nil
	}
	out := new(AttacknetRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttacknetRunStatus) DeepCopyInto(out *AttacknetRunStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.ActiveCampaign != nil {
		in, out := &in.ActiveCampaign, &out.ActiveCampaign
		*out = new(string)
		**out = **in
	}
	if in.ScheduleRef != nil {
		in, out := &in.ScheduleRef, &out.ScheduleRef
		*out = new(ScheduleReference)
		**out = **in
	}
	if in.ScheduleSummary != nil {
		in, out := &in.ScheduleSummary, &out.ScheduleSummary
		*out = new(ScheduleSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.ActiveChild != nil {
		in, out := &in.ActiveChild, &out.ActiveChild
		*out = new(ActiveRunChild)
		(*in).DeepCopyInto(*out)
	}
	if in.ResolvedCampaigns != nil {
		in, out := &in.ResolvedCampaigns, &out.ResolvedCampaigns
		*out = make([]ResolvedCampaign, len(*in))
		copy(*out, *in)
	}
	if in.Decisions != nil {
		in, out := &in.Decisions, &out.Decisions
		*out = make([]v1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BudgetUsage != nil {
		in, out := &in.BudgetUsage, &out.BudgetUsage
		*out = new(BudgetUsage)
		**out = **in
	}
	if in.IdentityDivergence != nil {
		in, out := &in.IdentityDivergence, &out.IdentityDivergence
		*out = new(IdentityDivergence)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityTransitions != nil {
		in, out := &in.IdentityTransitions, &out.IdentityTransitions
		*out = make([]IdentityTransition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TerminalClassification != nil {
		in, out := &in.TerminalClassification, &out.TerminalClassification
		*out = new(TerminalClassification)
		(*in).DeepCopyInto(*out)
	}
	if in.Cleanup != nil {
		in, out := &in.Cleanup, &out.Cleanup
		*out = new(RunCleanup)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttacknetRunStatus.
func (in *AttacknetRunStatus) DeepCopy() *AttacknetRunStatus {
	if in == nil {
		return nil
	}
	out := new(AttacknetRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributionPolicy) DeepCopyInto(out *AttributionPolicy) {
	*out = *in
	if in.AllowedTerminalStates != nil {
		in, out := &in.AllowedTerminalStates, &out.AllowedTerminalStates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributionPolicy.
func (in *AttributionPolicy) DeepCopy() *AttributionPolicy {
	if in == nil {
		return nil
	}
	out := new(AttributionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetUsage) DeepCopyInto(out *BudgetUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetUsage.
func (in *BudgetUsage) DeepCopy() *BudgetUsage {
	if in == nil {
		return nil
	}
	out := new(BudgetUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CampaignAdmission) DeepCopyInto(out *CampaignAdmission) {
	*out = *in
	in.NetworkInventory.DeepCopyInto(&out.NetworkInventory)
	in.AdmittedAt.DeepCopyInto(&out.AdmittedAt)
	if in.SignerSetRewardCycle != nil {
		in, out := &in.SignerSetRewardCycle, &out.SignerSetRewardCycle
		*out = new(int64)
		**out = **in
	}
	if in.SignerSetTotalWeight != nil {
		in, out := &in.SignerSetTotalWeight, &out.SignerSetTotalWeight
		*out = new(float64)
		**out = **in
	}
	if in.SignerImpact != nil {
		in, out := &in.SignerImpact, &out.SignerImpact
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.MinerImpact != nil {
		in, out := &in.MinerImpact, &out.MinerImpact
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CampaignAdmission.
func (in *CampaignAdmission) DeepCopy() *CampaignAdmission {
	if in == nil {
		return nil
	}
	out := new(CampaignAdmission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CampaignAssertion) DeepCopyInto(out *CampaignAssertion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CampaignAssertion.
func (in *CampaignAssertion) DeepCopy() *CampaignAssertion {
	if in == nil {
		return nil
	}
	out := new(CampaignAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CampaignCatalogEntry) DeepCopyInto(out *CampaignCatalogEntry) {
	*out = *in
	if in.ExpectedGeneration != nil {
		in, out := &in.ExpectedGeneration, &out.ExpectedGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CampaignCatalogEntry.
func (in *CampaignCatalogEntry) DeepCopy() *CampaignCatalogEntry {
	if in == nil {
		return nil
	}
	out := new(CampaignCatalogEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosReference) DeepCopyInto(out *ChaosReference) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosReference.
func (in *ChaosReference) DeepCopy() *ChaosReference {
	if in == nil {
		return nil
	}
	out := new(ChaosReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanupEvidence) DeepCopyInto(out *CleanupEvidence) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanupEvidence.
func (in *CleanupEvidence) DeepCopy() *CleanupEvidence {
	if in == nil {
		return nil
	}
	out := new(CleanupEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultCampaign) DeepCopyInto(out *FaultCampaign) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultCampaign.
func (in *FaultCampaign) DeepCopy() *FaultCampaign {
	if in == nil {
		return nil
	}
	out := new(FaultCampaign)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FaultCampaign) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultCampaignList) DeepCopyInto(out *FaultCampaignList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FaultCampaign, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultCampaignList.
func (in *FaultCampaignList) DeepCopy() *FaultCampaignList {
	if in == nil {
		return nil
	}
	out := new(FaultCampaignList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FaultCampaignList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultCampaignSpec) DeepCopyInto(out *FaultCampaignSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	in.Fault.DeepCopyInto(&out.Fault)
	out.Safety = in.Safety
	if in.EffectAssertions != nil {
		in, out := &in.EffectAssertions, &out.EffectAssertions
		*out = make([]CampaignAssertion, len(*in))
		copy(*out, *in)
	}
	if in.RecoveryAssertions != nil {
		in, out := &in.RecoveryAssertions, &out.RecoveryAssertions
		*out = make([]CampaignAssertion, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultCampaignSpec.
func (in *FaultCampaignSpec) DeepCopy() *FaultCampaignSpec {
	if in == nil {
		return nil
	}
	out := new(FaultCampaignSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultCampaignStatus) DeepCopyInto(out *FaultCampaignStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Admission != nil {
		in, out := &in.Admission, &out.Admission
		*out = new(CampaignAdmission)
		(*in).DeepCopyInto(*out)
	}
	if in.ResolvedTargets != nil {
		in, out := &in.ResolvedTargets, &out.ResolvedTargets
		*out = make([]ResolvedTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CapabilityEvidence != nil {
		in, out := &in.CapabilityEvidence, &out.CapabilityEvidence
		*out = make([]v1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Chaos != nil {
		in, out := &in.Chaos, &out.Chaos
		*out = new(ChaosReference)
		(*in).DeepCopyInto(*out)
	}
	if in.InjectedAt != nil {
		in, out := &in.InjectedAt, &out.InjectedAt
		*out = (*in).DeepCopy()
	}
	if in.ActualInjection != nil {
		in, out := &in.ActualInjection, &out.ActualInjection
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.ProbeArtifacts != nil {
		in, out := &in.ProbeArtifacts, &out.ProbeArtifacts
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EffectResults != nil {
		in, out := &in.EffectResults, &out.EffectResults
		*out = make([]v1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RecoveryResults != nil {
		in, out := &in.RecoveryResults, &out.RecoveryResults
		*out = make([]v1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cleanup != nil {
		in, out := &in.Cleanup, &out.Cleanup
		*out = new(CleanupEvidence)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityDivergence != nil {
		in, out := &in.IdentityDivergence, &out.IdentityDivergence
		*out = new(IdentityDivergence)
		(*in).DeepCopyInto(*out)
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultCampaignStatus.
func (in *FaultCampaignStatus) DeepCopy() *FaultCampaignStatus {
	if in == nil {
		return nil
	}
	out := new(FaultCampaignStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultSafety) DeepCopyInto(out *FaultSafety) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultSafety.
func (in *FaultSafety) DeepCopy() *FaultSafety {
	if in == nil {
		return nil
	}
	out := new(FaultSafety)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultSpec) DeepCopyInto(out *FaultSpec) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(intstr.IntOrString)
		**out = **in
	}
	in.Parameters.DeepCopyInto(&out.Parameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultSpec.
func (in *FaultSpec) DeepCopy() *FaultSpec {
	if in == nil {
		return nil
	}
	out := new(FaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultTarget) DeepCopyInto(out *FaultTarget) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultTarget.
func (in *FaultTarget) DeepCopy() *FaultTarget {
	if in == nil {
		return nil
	}
	out := new(FaultTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityDifference) DeepCopyInto(out *IdentityDifference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityDifference.
func (in *IdentityDifference) DeepCopy() *IdentityDifference {
	if in == nil {
		return nil
	}
	out := new(IdentityDifference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityDivergence) DeepCopyInto(out *IdentityDivergence) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.Differences != nil {
		in, out := &in.Differences, &out.Differences
		*out = make([]IdentityDifference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityDivergence.
func (in *IdentityDivergence) DeepCopy() *IdentityDivergence {
	if in == nil {
		return nil
	}
	out := new(IdentityDivergence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityTransition) DeepCopyInto(out *IdentityTransition) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityTransition.
func (in *IdentityTransition) DeepCopy() *IdentityTransition {
	if in == nil {
		return nil
	}
	out := new(IdentityTransition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinimizationSpec) DeepCopyInto(out *MinimizationSpec) {
	*out = *in
	if in.Retained != nil {
		in, out := &in.Retained, &out.Retained
		*out = make([]RetainedInstruction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinimizationSpec.
func (in *MinimizationSpec) DeepCopy() *MinimizationSpec {
	if in == nil {
		return nil
	}
	out := new(MinimizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInventory) DeepCopyInto(out *NetworkInventory) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]AdmittedActorIdentity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInventory.
func (in *NetworkInventory) DeepCopy() *NetworkInventory {
	if in == nil {
		return nil
	}
	out := new(NetworkInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbePort) DeepCopyInto(out *ProbePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbePort.
func (in *ProbePort) DeepCopy() *ProbePort {
	if in == nil {
		return nil
	}
	out := new(ProbePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeService) DeepCopyInto(out *ProbeService) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ProbePort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeService.
func (in *ProbeService) DeepCopy() *ProbeService {
	if in == nil {
		return nil
	}
	out := new(ProbeService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeSpec) DeepCopyInto(out *ProbeSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalServices != nil {
		in, out := &in.AdditionalServices, &out.AdditionalServices
		*out = make([]ProbeService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeSpec.
func (in *ProbeSpec) DeepCopy() *ProbeSpec {
	if in == nil {
		return nil
	}
	out := new(ProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplaySpec) DeepCopyInto(out *ReplaySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplaySpec.
func (in *ReplaySpec) DeepCopy() *ReplaySpec {
	if in == nil {
		return nil
	}
	out := new(ReplaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedCampaign) DeepCopyInto(out *ResolvedCampaign) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedCampaign.
func (in *ResolvedCampaign) DeepCopy() *ResolvedCampaign {
	if in == nil {
		return nil
	}
	out := new(ResolvedCampaign)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedTarget) DeepCopyInto(out *ResolvedTarget) {
	*out = *in
	if in.RequestedImage != nil {
		in, out := &in.RequestedImage, &out.RequestedImage
		*out = new(string)
		**out = **in
	}
	if in.ResolvedImageID != nil {
		in, out := &in.ResolvedImageID, &out.ResolvedImageID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedTarget.
func (in *ResolvedTarget) DeepCopy() *ResolvedTarget {
	if in == nil {
		return nil
	}
	out := new(ResolvedTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResumeSpec) DeepCopyInto(out *ResumeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResumeSpec.
func (in *ResumeSpec) DeepCopy() *ResumeSpec {
	if in == nil {
		return nil
	}
	out := new(ResumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetainedInstruction) DeepCopyInto(out *RetainedInstruction) {
	*out = *in
	if in.RemovedTargets != nil {
		in, out := &in.RemovedTargets, &out.RemovedTargets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemovedParameters != nil {
		in, out := &in.RemovedParameters, &out.RemovedParameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetainedInstruction.
func (in *RetainedInstruction) DeepCopy() *RetainedInstruction {
	if in == nil {
		return nil
	}
	out := new(RetainedInstruction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunBudgets) DeepCopyInto(out *RunBudgets) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunBudgets.
func (in *RunBudgets) DeepCopy() *RunBudgets {
	if in == nil {
		return nil
	}
	out := new(RunBudgets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunCleanup) DeepCopyInto(out *RunCleanup) {
	*out = *in
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunCleanup.
func (in *RunCleanup) DeepCopy() *RunCleanup {
	if in == nil {
		return nil
	}
	out := new(RunCleanup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunInstruction) DeepCopyInto(out *RunInstruction) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunInstruction.
func (in *RunInstruction) DeepCopy() *RunInstruction {
	if in == nil {
		return nil
	}
	out := new(RunInstruction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimePolicySpec) DeepCopyInto(out *RuntimePolicySpec) {
	*out = *in
	out.ConfigMapRef = in.ConfigMapRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimePolicySpec.
func (in *RuntimePolicySpec) DeepCopy() *RuntimePolicySpec {
	if in == nil {
		return nil
	}
	out := new(RuntimePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleReference) DeepCopyInto(out *ScheduleReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleReference.
func (in *ScheduleReference) DeepCopy() *ScheduleReference {
	if in == nil {
		return nil
	}
	out := new(ScheduleReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleSummary) DeepCopyInto(out *ScheduleSummary) {
	*out = *in
	if in.SignerSetRewardCycle != nil {
		in, out := &in.SignerSetRewardCycle, &out.SignerSetRewardCycle
		*out = new(int64)
		**out = **in
	}
	if in.SignerSetTotalWeight != nil {
		in, out := &in.SignerSetTotalWeight, &out.SignerSetTotalWeight
		*out = new(float64)
		**out = **in
	}
	in.NetworkInventory.DeepCopyInto(&out.NetworkInventory)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleSummary.
func (in *ScheduleSummary) DeepCopy() *ScheduleSummary {
	if in == nil {
		return nil
	}
	out := new(ScheduleSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetwork) DeepCopyInto(out *StacksNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetwork.
func (in *StacksNetwork) DeepCopy() *StacksNetwork {
	if in == nil {
		return nil
	}
	out := new(StacksNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkDefaults) DeepCopyInto(out *StacksNetworkDefaults) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerSecurityContext != nil {
		in, out := &in.ContainerSecurityContext, &out.ContainerSecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkDefaults.
func (in *StacksNetworkDefaults) DeepCopy() *StacksNetworkDefaults {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkList) DeepCopyInto(out *StacksNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkList.
func (in *StacksNetworkList) DeepCopy() *StacksNetworkList {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkSpec) DeepCopyInto(out *StacksNetworkSpec) {
	*out = *in
	in.Defaults.DeepCopyInto(&out.Defaults)
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetrySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Probe != nil {
		in, out := &in.Probe, &out.Probe
		*out = new(ProbeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]ActorSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkSpec.
func (in *StacksNetworkSpec) DeepCopy() *StacksNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkStatus) DeepCopyInto(out *StacksNetworkStatus) {
	*out = *in
	if in.InventoryObservedAt != nil {
		in, out := &in.InventoryObservedAt, &out.InventoryObservedAt
		*out = (*in).DeepCopy()
	}
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]ActorStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkStatus.
func (in *StacksNetworkStatus) DeepCopy() *StacksNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StopPolicy) DeepCopyInto(out *StopPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StopPolicy.
func (in *StopPolicy) DeepCopy() *StopPolicy {
	if in == nil {
		return nil
	}
	out := new(StopPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]corev1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetrySpec) DeepCopyInto(out *TelemetrySpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetrySpec.
func (in *TelemetrySpec) DeepCopy() *TelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(TelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerminalClassification) DeepCopyInto(out *TerminalClassification) {
	*out = *in
	if in.Observations != nil {
		in, out := &in.Observations, &out.Observations
		*out = make([]v1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerminalClassification.
func (in *TerminalClassification) DeepCopy() *TerminalClassification {
	if in == nil {
		return nil
	}
	out := new(TerminalClassification)
	in.DeepCopyInto(out)
	return out
}
