apiVersion: testing.stacks.org/v1beta1
kind: BurnchainPolicy
metadata:
  name: adversarial-signer
spec:
  networkRef: adversarial-signer
  bitcoinNodeRef: bitcoin
  bootstrapHeight: 245
  cadence: 5s
  destinationSelection: fixed
  fixedDestinationIndex: 0
  destinations:
    - walletName: attacknet-faucet
      address: mipcBbFg9gMiCh81Kj8tqqdgoZub1ZJRfn
  protocolSchedule:
    epochs:
      - {name: epoch-2-0, startHeight: 0}
      - {name: epoch-2-5, startHeight: 203}
      - {name: epoch-3-0, startHeight: 225}
      - {name: epoch-3-1, startHeight: 227}
    rewardCycle: {firstHeight: 0, cycleLength: 20, prepareLength: 5}
  rpc: {timeout: 5s, minimumBackoff: 1s, maximumBackoff: 5s}
